name: Deploy Images to GHCR

on:
  push:
    branches:
      - dd
  workflow_dispatch:

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Build Image"
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: "ghcr.io/vaaski/fuckvoicemessages:latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max
